# Generated by Django 3.2.5 on 2021-10-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_author_authoruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authorUser',
        ),
    ]
